# -*- coding: utf-8 -*-
"""
A hardware-adaptive reader for SNOWPACK .pro files using xarray.

This module provides the `SnowpackProfile` class for parsing, processing,
and analyzing data from .pro files generated by the SNOWPACK model. It is
designed to automatically leverage available hardware for optimal performance.

Hardware Acceleration
---------------------
- **GPU Acceleration**: If a compatible NVIDIA GPU and the `cupy` library are
  detected, all heavy numerical computations are offloaded to the GPU for a
  significant speedup. The `cupy` library must be installed separately
  (e.g., `uv pip install cupy-cuda12x`). A full CUDA Toolkit installation
  is also required.
- **CPU Fallback**: If no GPU is available or `cupy` is not installed, the
  script seamlessly falls back to using the CPU with `numpy` for all
  calculations, ensuring functionality across different hardware environments.

Key Features
------------
- Parses station metadata and time-series profile data from .pro files.
- Stores data in a multi-dimensional `xarray.Dataset`, enabling efficient,
  vectorized processing on either CPU or GPU.
- Automatically calculates the critical cut length (`rc_flat`) using a
  vectorized approach that runs on the detected hardware.
- Provides a powerful summary method (`get_profile_summary`) to extract key
  statistics (e.g., min, max, weighted_mean) for specific time ranges and
  snowpack sections.
- Supports user-defined functions for custom summary statistics.

Typical Workflow
----------------
1. Instantiate `SnowpackProfile` with a file path. The script automatically
   detects the hardware and loads the data.
2. The core data is stored in the `.data` attribute as an `xarray.Dataset`
   containing either `numpy` or `cupy` arrays.
3. Use methods like `get_profile_summary()` to generate a time-series
   DataFrame of summary statistics for specified snowpack parameters.
   
Last Updated: July 2nd, 2025
@author: Ron Simenhois
"""

import logging
import os
from typing import Dict, Optional, List, Tuple, Any

# --- Hardware-Adaptive Array Library ---
# This block detects if a GPU is available and chooses the appropriate library.
# All subsequent code uses the 'xp' alias for array operations, making the
# script hardware-agnostic.
try:
    import cupy as xp
    # A simple operation to confirm the library can communicate with the GPU
    _ = xp.arange(1)
    GPU_AVAILABLE = True
    print("✅ GPU detected. Using cupy for accelerated calculations.")
except (ImportError, RuntimeError):
    import numpy as xp
    GPU_AVAILABLE = False
    print("ℹ️ No GPU or cupy found. Falling back to CPU using numpy.")
# ---

import pandas as pd
import xarray as xr
from tqdm import tqdm

# Configure logging for the module
logger = logging.getLogger(__name__)

# --- Static Mappings ---

# Maps header keys from .pro files to human-readable dictionary keys.
# Source: https://snowpack.slf.ch/doc-release/html/snowpackio.html
HEADER_MAP = {
    'Altitude=': 'altitude',
    'Latitude=': 'latitude',
    'Longitude=': 'longitude',
    'SlopeAngle=': 'slopeAngle',
    'SlopeAzi=': 'slopeAzi',
    'StationName=': 'stationName'
}

# Static mapping of parameter codes to human-readable names.
# Source: https://snowpack.slf.ch/doc-release/html/snowpackio.html
PARAM_CODES = {
    "0500": "timestamp", 
    "0501": "height", 
    "0504": "element_ID",
    "0502": "density", 
    "0503": "temperature", 
    "0506": "lwc",
    "0508": "dendricity", 
    "0509": "sphericity", 
    "0510": "coord_number",
    "0511": "bond_size", 
    "0512": "grain_size", 
    "0513": "grain_type",
    # "0514": "sh_at_surface",
    "0515": "ice_content", 
    "0516": "air_content",
    "0517": "stress", 
    "0518": "viscosity", 
    "0520": "temperature_gradient",
    "0523": "viscous_deformation_rate", 
    # "0530": "stab_indices",
    "0531": "stab_deformation_rate", 
    "0532": "sn38", 
    "0533": "sk38",
    "0534": "hand_hardness", 
    "0535": "opt_equ_grain_size",
    "0601": "shear_strength", 
    "0602": "gs_difference", 
    "0603": "hardness_difference",
    "0604": "ssi", 
    "1501": "height_nodes", 
    "1532": "sn38_nodes",
    "1533": "sk38_nodes", 
    "0540": "date_of_birth",
    "0607": "accumulated_temperature_gradient", 
    "9999": "rc_flat" # Placeholder for calculated rc_flat
}

# --- End Static Mappings ---

class SnowpackProfile:
    """
    Reads, parses, and represents a SNOWPACK .pro file.

    This class handles the entire lifecycle of a .pro file, from reading and
    parsing to performing hardware-accelerated numerical computations.

    Attributes:
        filename (str): The path to the input .pro file.
        metadata (Dict): Station parameters parsed from the file header.
        data (Optional[xr.Dataset]): An xarray Dataset containing all profile
            data. The underlying arrays will be `cupy` arrays if a GPU is
            used, otherwise they will be `numpy` arrays.
    """

    def __init__(self, filename: str):
        """
        Initializes the reader and processes the specified file.

        Args:
            filename (str): The full path to the .pro file.
        """
        self.filename: str = filename
        self.metadata: Dict = {}
        self.data: Optional[xr.Dataset] = None
        self._read_profile()

    def __len__(self) -> int:
        """Returns the number of profiles (timestamps) in the dataset."""
        if self.data is None:
            return 0
        return len(self.data.timestamp)

    def __repr__(self) -> str:
        """Provides a developer-friendly representation of the object."""
        device = "GPU" if GPU_AVAILABLE else "CPU"
        return f"<SnowpackProfile(filename='{self.filename}', profiles={len(self)}, device='{device}')>"

    def __str__(self) -> str:
        """Provides a user-friendly summary of the snow profile data."""
        if self.data is None:
            return f"SnowpackProfile for '{self.filename}' (no data loaded or failed to parse)"
        station_name = self.metadata.get('stationName', 'Unknown Station')
        device = "GPU" if GPU_AVAILABLE else "CPU"
        return (f"Snow Profile for Station: '{station_name}'\n"
                f"File: '{self.filename}'\n"
                f"Processing On: {device}\n"
                f"Available Profiles: {len(self)}\n"
                f"Parameters: {list(self.data.data_vars)}")

    def _read_profile(self):
        """
        Orchestrates the reading and parsing of the entire .pro file.

        This is a CPU-bound operation involving file I/O and string parsing.
        """
        if not os.path.exists(self.filename):
            logger.error(f"File not found: {self.filename}")
            return
        in_header, in_data = False, False
        temp_profiles: List[Dict] = []
        current_ts_data: Dict = {}

        with open(self.filename, 'r') as f:
            for line in tqdm(f, desc=f"Reading {os.path.basename(self.filename)}"):
                line = line.strip()
                if not line:
                    continue

                if line == '[STATION_PARAMETERS]':
                    in_header, in_data = True, False
                elif line == '[DATA]':
                    in_header, in_data = False, True
                elif line.startswith('['):
                    in_header, in_data = False, False
                elif in_header:
                    self._parse_header_line(line)
                elif in_data:
                    is_new_ts, timestamp_key = self._is_new_timestamp_line(line)
                    if is_new_ts:
                        if current_ts_data:
                            temp_profiles.append(current_ts_data)
                        current_ts_data = {'timestamp': timestamp_key}
                    else:
                        self._parse_data_line(line, current_ts_data)

        if current_ts_data:
            temp_profiles.append(current_ts_data)
        if not temp_profiles:
            logger.warning("No data was parsed from the file.")
            return

        self._create_dataset_from_profiles(temp_profiles)
        if self.data is not None:
            self._compute_and_add_rc_flat_vectorized()

    def _create_dataset_from_profiles(self, profiles: List[Dict]):
        """
        Converts parsed data into an xarray.Dataset.

        This method builds numpy arrays from the parsed data, then moves them
        to the GPU as cupy arrays if a GPU is available, before finally
        creating the xarray Dataset.

        Args:
            profiles (List[Dict]): A list where each dict holds one timestamp's data.
        """
        timestamps = pd.to_datetime([p['timestamp'] for p in profiles], format='%d.%m.%Y %H:%M:%S', errors='coerce')
        valid_indices = ~pd.isna(timestamps)
        profiles = [p for i, p in enumerate(profiles) if valid_indices[i]]
        timestamps = timestamps.dropna()

        if not profiles:
            logger.warning("No valid profiles remaining after date parsing.")
            return

        all_params = sorted(list(set(key for p in profiles for key in p if key != 'timestamp')))
        max_layers = max((len(p.get('height', [])) for p in profiles), default=0)

        data_vars = {}
        # Use standard numpy for initial data assembly on the CPU
        import numpy as np
        for param in all_params:
            numpy_arr = np.full((len(profiles), max_layers), np.nan, dtype=np.float32)
            data_vars[param] = (("timestamp", "layer_index"), numpy_arr)

        for i, profile in enumerate(tqdm(profiles, desc="Assembling Data")):
            num_layers = len(profile.get('height', []))
            for param, (dims, arr) in data_vars.items():
                if param in profile:
                    values = profile.get(param)
                    if values is not None:
                        # Ensure values are numpy arrays before assignment
                        if not isinstance(values, np.ndarray):
                            values = np.array(values)
                        arr[i, :num_layers] = values[:num_layers]

        # If GPU is available, move the arrays to the device before creating the Dataset
        if GPU_AVAILABLE:
            tqdm_desc = "Moving data to GPU"
            for param, (dims, arr) in tqdm(data_vars.items(), desc=tqdm_desc):
                data_vars[param] = (dims, xp.asarray(arr))

        self.data = xr.Dataset(data_vars, coords={'timestamp': timestamps, 'layer_index': xp.arange(max_layers)})
        self.data = self.data.sortby('timestamp')

    def _parse_header_line(self, line: str):
        """Parses a single line from the [STATION_PARAMETERS] section."""
        for key, value in HEADER_MAP.items():
            if line.startswith(key):
                try:
                    self.metadata[value] = line.split('=', 1)[1].strip()
                except IndexError:
                    logger.warning(f"Could not parse header line: {line}")

    def _is_new_timestamp_line(self, line: str) -> Tuple[bool, Optional[str]]:
        """Checks if a data line marks the beginning of a new profile."""
        parts = line.split(',', 1)
        if parts[0] == "0500":  # '0500' is the code for a timestamp
            return True, parts[1]
        return False, None

    def _parse_data_line(self, line: str, current_ts_data: Dict):
        """
        Parses a single data line containing layer data for a parameter.

        Args:
            line (str): A comma-separated line (code, name, values...).
            current_ts_data (Dict): The dictionary for the current timestamp.
        """
        try:
            parts = line.split(',')
            code = parts[0]
            param_name = PARAM_CODES.get(code)
            if param_name:
                # Data is parsed into standard python/numpy types on CPU first
                import numpy as np
                current_ts_data[param_name] = np.array(parts[2:], dtype=float)
        except (ValueError, IndexError) as e:
            logger.warning(f"Could not parse data line: '{line}' - Error: {e}")

    def _compute_and_add_rc_flat_vectorized(self):
        """
        Calculates rc_flat for all profiles in a single vectorized operation.

        This method leverages the detected hardware (CPU or GPU) via the `xp`
        array alias to perform array-based arithmetic. This is the primary
        computationally intensive step that benefits from GPU acceleration.
        It corrects the data at the source by setting the physically
        meaningless surface `rc_flat` value to a large number.
        """
        required_vars = {'density', 'grain_size', 'shear_strength', 'height'}
        if not required_vars.issubset(self.data.data_vars):
            logger.warning(f"Skipping rc_flat calculation due to missing variables.")
            return

        # --- Physical Constants ---
        RHO_ICE, GS_0, G, A, B = 917.0, 0.00125, 9.81, 4.6e-9, -2.0

        # --- Data Preparation ---
        # These are xarray.DataArray objects wrapping either numpy or cupy arrays
        height, density, grain_size, shear_strength = (
            self.data['height'], self.data['density'],
            self.data['grain_size'], self.data['shear_strength']
        )

        # --- Calculations (performed on either CPU or GPU via `xp` alias) ---
        height_of_bottom = height.shift(layer_index=1, fill_value=0)
        thick = height - height_of_bottom
        layer_load = (density * thick * G)
        load = layer_load.reindex(layer_index=layer_load.layer_index[::-1]).cumsum(dim='layer_index').reindex(layer_index=layer_load.layer_index)

        total_thick_above = self.data['height'].max(dim='layer_index', skipna=True) - height
        
        rho_sl_raw = load / (total_thick_above * G)
        
        if GPU_AVAILABLE:
            rho_sl_numpy = rho_sl_raw.to_numpy()
            rho_sl_cpu_da = xr.DataArray(rho_sl_numpy, dims=rho_sl_raw.dims, coords=rho_sl_raw.coords)
            rho_sl_filled_cpu = rho_sl_cpu_da.bfill(dim='layer_index').ffill(dim='layer_index')
            rho_sl_gpu = xp.asarray(rho_sl_filled_cpu.values)
            rho_sl = xr.DataArray(rho_sl_gpu, dims=rho_sl_raw.dims, coords=rho_sl_raw.coords)
        else:
            rho_sl = rho_sl_raw.bfill(dim='layer_index').ffill(dim='layer_index')

        tau_p = shear_strength * 1000.0
        gs = grain_size * 0.001
        e_prime = 5.07e9 * (rho_sl / RHO_ICE)**5.13 / (1 - 0.2**2)
        dsl_over_sigman = 1.0 / (G * rho_sl)
        term1_under = A * (density / RHO_ICE * gs / GS_0)**B
        term2_under = 2 * tau_p * e_prime * dsl_over_sigman

        term1_data = term1_under.data.copy()
        term1_data[term1_data <= 0] = xp.nan
        term1_sqrt = xp.sqrt(term1_data)
        term1 = xr.DataArray(term1_sqrt, dims=term1_under.dims, coords=term1_under.coords)

        term2_data = term2_under.data.copy()
        term2_data[term2_data <= 0] = xp.nan
        term2_sqrt = xp.sqrt(term2_data)
        term2 = xr.DataArray(term2_sqrt, dims=term2_under.dims, coords=term2_under.coords)
        
        rc_flat_combined = term1 * term2
        rc_flat_filled_data = xp.nan_to_num(rc_flat_combined.data, nan=9999.0)
        rc_flat_da = xr.DataArray(rc_flat_filled_data, dims=rc_flat_combined.dims, coords=rc_flat_combined.coords)

        # Set rc_flat for the surface layer to 9999.0 as it is not physically meaningful
        max_heights = height.max(dim='layer_index', skipna=True)
        is_not_surface = height < max_heights
        
        # --- FIX for cupy incompatibility with xarray.where() ---
        # This final .where() call also needs to be handled carefully on the GPU.
        if GPU_AVAILABLE:
            # Use cupy's native where on the raw arrays
            final_data = xp.where(is_not_surface.data, rc_flat_da.data, 9999.0)
            rc_flat_da = xr.DataArray(final_data, dims=rc_flat_da.dims, coords=rc_flat_da.coords)
        else:
            # The xarray method is fine for numpy
            rc_flat_da = rc_flat_da.where(is_not_surface, 9999.0)
        # --- End Fix ---

        # Add the final calculated data back to the main dataset
        self.data['rc_flat'] = rc_flat_da.transpose('timestamp', 'layer_index')

    def profile_to_dataframe(self, timestamp: str) -> Optional[pd.DataFrame]:
        """
        Extracts a single profile into a pandas DataFrame.

        This method selects the profile with the timestamp nearest to the
        one provided. If data is on the GPU, it's transferred back to the
        CPU before creating the DataFrame.

        Args:
            timestamp (str): The desired timestamp (e.g., 'YYYY-MM-DD HH:MM:SS').

        Returns:
            Optional[pd.DataFrame]: A DataFrame for the selected profile, or
            None if no data is available.
        """
        if self.data is None:
            return None
        try:
            profile_data = self.data.sel(timestamp=timestamp, method='nearest')
        except (KeyError, ValueError):
            return None

        if GPU_AVAILABLE:
            profile_data_cpu = profile_data.as_numpy()
            df = profile_data_cpu.to_dataframe().reset_index()
        else:
            df = profile_data.to_dataframe().reset_index()

        df.dropna(subset=['height'], inplace=True)
        if 'height' in df.columns:
            df.set_index('height', inplace=True)
            df = df[~df.index.duplicated(keep='last')]
        return df.drop(columns=['timestamp', 'layer_index'], errors='ignore')

    def get_profile_summary(
        self,
        parameters_to_calculate: Dict[str, Any],
        from_height: Optional[float] = None,
        above_or_below: str = 'above',
        start_date: Optional[str] = None,
        end_date: Optional[str] = None
    ) -> pd.DataFrame:
        """
        Extracts summary statistics for specified parameters.

        This method processes the profile closest to noon for each day. It first
        transfers the necessary data slice from GPU to CPU (if applicable), then
        performs summary calculations using pandas.

        Args:
            parameters_to_calculate (Dict[str, Any]): A dictionary mapping a
                new column name to a calculation type. The type can be a string
                ('min', 'max', 'mean', etc.) or a callable function that accepts
                a DataFrame and returns a scalar.
            from_height (Optional[float]): Height in meters to slice the snowpack.
                If None, the entire profile is used. Defaults to None.
            above_or_below (str): Section to analyze ('above' or 'below')
                the `from_height`. Defaults to 'above'.
            start_date (Optional[str]): Start date for the summary
                (e.g., 'YYYY-MM-DD'). Defaults to None.
            end_date (Optional[str]): End date for the summary
                (e.g., 'YYYY-MM-DD'). Defaults to None.

        Returns:
            pd.DataFrame: A DataFrame with a 'date' index and columns for each
            requested summary statistic.
        """
        if self.data is None or self.data.timestamp.size == 0:
            return pd.DataFrame()

        data_in_range = self.data
        if start_date or end_date:
            try:
                s_date = pd.to_datetime(start_date) if start_date else None
                e_date = pd.to_datetime(end_date) if end_date else None
                time_slice = slice(s_date, e_date)
                data_in_range = data_in_range.sel(timestamp=time_slice)
            except Exception:
                return pd.DataFrame()
        if data_in_range.timestamp.size == 0:
            return pd.DataFrame()

        if GPU_AVAILABLE:
            data_in_range_cpu = data_in_range.as_numpy()
            full_df = data_in_range_cpu.to_dataframe().reset_index()
        else:
            full_df = data_in_range.to_dataframe().reset_index()

        # --- The rest of the function uses pandas and is CPU-bound ---
        noon_time = full_df['timestamp'].dt.normalize() + pd.Timedelta(hours=12)
        full_df['time_from_noon'] = (full_df['timestamp'] - noon_time).abs()
        closest_indices = full_df.loc[full_df.groupby(full_df['timestamp'].dt.date)['time_from_noon'].idxmin()]
        noon_df = closest_indices.copy()
        if noon_df.empty:
            return pd.DataFrame()
        noon_df['date'] = noon_df['timestamp'].dt.normalize()

        summary_list = []
        for ts in noon_df['timestamp']:
            summary_row = {'date': ts.normalize()}
            profile_layers = full_df[full_df['timestamp'] == ts].copy()
            if from_height is not None:
                profile_layers = profile_layers[profile_layers['height'] >= from_height] if above_or_below == 'above' else profile_layers[profile_layers['height'] < from_height]
            if not profile_layers.empty:
                profile_layers = profile_layers.sort_values('height').copy()
                profile_layers['thickness'] = profile_layers['height'].diff()
                base_h = from_height if (from_height is not None and above_or_below == 'above') else 0
                if not profile_layers.empty:
                    first_row_index = profile_layers.index[0]
                    profile_layers.loc[first_row_index, 'thickness'] = profile_layers['height'].iloc[0] - base_h

            for name, calc in parameters_to_calculate.items():
                if callable(calc):
                    try:
                        summary_row[name] = calc(profile_layers)
                    except Exception as e:
                        logger.warning(f"Custom function for '{name}' failed: {e}")
                    continue

                # Parse the parameter and calculation type from the input dictionary
                if isinstance(calc, str):
                    param, calc_type = name.split('-')[0], calc
                elif isinstance(calc, tuple):
                    param, calc_type = calc
                else:
                    continue # Skip unknown formats

                if param in profile_layers:
                    series = profile_layers[param].dropna()
                    if series.empty:
                        continue
                    
                    # --- FIX: Correctly add <param>-height for min/max ---
                    if calc_type == 'min':
                        summary_row[name] = series.min()
                        # Check if 'height' column exists before trying to access it
                        if 'height' in profile_layers.columns:
                           summary_row[f"{name}-height"] = profile_layers.loc[series.idxmin()]['height']
                    elif calc_type == 'max':
                        summary_row[name] = series.max()
                        if 'height' in profile_layers.columns:
                           summary_row[f"{name}-height"] = profile_layers.loc[series.idxmax()]['height']
                    elif calc_type == 'mean':
                        summary_row[name] = series.mean()
                    elif calc_type == 'median':
                        summary_row[name] = series.median()
                    elif calc_type in ['weighted_mean', 'weighted_sum']:
                        weights = profile_layers.loc[series.index]['thickness']
                        weighted_sum_val = (series * weights).sum()
                        if calc_type == 'weighted_sum':
                            summary_row[name] = weighted_sum_val
                        elif weights.sum() > 0:
                            summary_row[name] = weighted_sum_val / weights.sum()
                    # --- End Fix ---
            summary_list.append(summary_row)

        if not summary_list:
            return pd.DataFrame()
        return pd.DataFrame(summary_list).set_index('date')



if __name__ == '__main__':
    # --- Example Usage ---
    # This block demonstrates a multi-step analysis:
    # 1. Find the daily minimum critical cut length (rc_flat) and its height.
    # 2. For each day, analyze the slab *above* that weak layer.
    # 3. Calculate the slab's weighted mean density (built-in stat) and
    #    a custom hand hardness metric (custom function).
    
    logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
    from glob import glob
    import random
    
    try:
        # Update this path to your data directory
        pro_files = glob("../data/snowpack/output/2024/**/*.pro", recursive=True)
        if not pro_files:
            raise FileNotFoundError("No .pro files found. Please update the glob path.")
        
        pro_path = random.choice(pro_files)
        logger.info(f"Selected file for demonstration: {pro_path}")
        
    except (FileNotFoundError, IndexError) as e:
        logger.error(f"Error finding a file to test: {e}. Please ensure files exist.")
        pro_path = None

    if pro_path:
        try:
            reader = SnowpackProfile(pro_path)
            print(f"\n{str(reader)}\n")

            # --- Step 1: Find the primary weak layer for each day ---
            print("--- Step 1: Locating the weakest layer (min rc_flat) for each day ---")
            # Define parameters for summary
            summary_parameters = {
                'rc_flat-min': ('rc_flat', 'min'),
                'height-max': ('height', 'max')
            }

            # The .pro year file is for the water year 2024, so we analyze February 2025
            weak_layer_df = reader.get_profile_summary(
                summary_parameters,
                start_date='2025-02-01',
                end_date='2025-02-28'
            )
            # Rename the height column for clarity
            weak_layer_df.rename(columns={'rc_flat-min-height': 'weak_layer_height'}, inplace=True)
            
            if weak_layer_df.empty:
                raise ValueError("No weak layer data found for the date range.")
            
            print("Weak layer location summary (first 5 days):")
            print(weak_layer_df.head())

            # --- Step 2: Analyze the slab properties above the weak layer ---
            print("\n--- Step 2: Analyzing the slab above the weak layer for each day ---")
            slab_analysis_results = []

            # Iterate through each day we have weak layer data for
            for date, row in tqdm(weak_layer_df.iterrows(), total=weak_layer_df.shape[0], desc="Analyzing Slabs"):
                weak_layer_height = row['weak_layer_height']
                
                # Run a new summary for this single day, focusing on the slab
                slab_summary = reader.get_profile_summary(
                    start_date=date.strftime('%Y-%m-%d'),
                    end_date=date.strftime('%Y-%m-%d'),
                    from_height=weak_layer_height,
                    above_or_below='above',
                    parameters_to_calculate={
                        # Use a built-in stat for weighted mean density
                        'slab_density_weighted_mean': ('density', 'weighted_mean'),
                        # Use a custom function for the specific hand hardness formula
                        'slab_log_hardness_mean': lambda df: (2**df['hand_hardness'] * df['thickness']).mean() if not df.empty and 'hand_hardness' in df else None
                    }
                )

                if not slab_summary.empty:
                    slab_analysis_results.append(slab_summary.iloc[0])

            # --- Step 3: Combine and display the results ---
            if slab_analysis_results:
                slab_df = pd.DataFrame(slab_analysis_results)
                # Combine the weak layer info with the slab analysis info
                final_df = weak_layer_df.join(slab_df, how='inner')

                print("\n--- Step 3: Combined Daily Weak Layer and Slab Analysis ---")
                print(final_df.head())
            else:
                print("\nCould not perform slab analysis.")

        except Exception as e:
            logger.error(f"An error occurred during analysis: {e}", exc_info=True)
