# -*- coding: utf-8 -*-
"""
A reader for SNOWPACK .pro files using the xarray library for efficiency.

This module provides a class, SnowpackProfile, for parsing, processing,
and analyzing data from .pro files generated by the SNOWPACK model. It is designed
to handle the specific format of these files, including metadata and layered
profile data for multiple timestamps.

The core data structure used is an xarray.Dataset, which allows for labeled,
multi-dimensional arrays that are ideal for scientific time-series data. This
approach enables highly efficient, vectorized computations, significantly
outperforming traditional row-by-row or profile-by-profile processing.

Key Features:
- Parses station metadata and time-series profile data from a .pro file upon
  initialization.
- Stores profile data in a multi-dimensional xarray.Dataset for highly
  efficient, vectorized processing.
- Automatically calculates the critical cut length for flat terrain (rc_flat) for
  all profiles in a single vectorized operation.
- Provides methods to convert individual profiles into pandas DataFrames for
  easy analysis.
- Includes a highly optimized, vectorized summary method to extract key statistics
  (min, max, mean, etc.) across all profiles.

Workflow:
1.  Instantiate the `SnowpackProfile` with the path to a .pro file. The data
    is read and processed into an xarray.Dataset immediately.
2.  Access metadata via the `.metadata` attribute and the core data via the
    `.data` (xarray.Dataset) attribute.
3.  Use methods like `list_timestamps()` or `profile_to_dataframe()` to access
    the parsed data.
4.  Use `get_profile_summary()` to generate a time-series DataFrame of summary
    statistics for specified snowpack parameters.

Dependencies:
- pandas
- numpy
- xarray
- tqdm

Last Updated: July 2nd, 2025
@author: Avalanche
"""
import logging
import os
from typing import Dict, Optional, List, Tuple

import numpy as np
import pandas as pd
import xarray as xr
from tqdm import tqdm

# Configure logging for the module
logger = logging.getLogger(__name__)

# Static mapping of header keys to human-readable names.
# Source: https://snowpack.slf.ch/doc-release/html/snowpackio.html
HEADER_MAP = {
    'Altitude=': 'altitude',
    'Latitude=': 'latitude',
    'Longitude=': 'longitude',
    'SlopeAngle=': 'slopeAngle',
    'SlopeAzi=': 'slopeAzi',
    'StationName=': 'stationName'
}

# Static mapping of parameter codes to human-readable names.
# Source: https://snowpack.slf.ch/doc-release/html/snowpackio.html
PARAM_CODES = {
    "0500": "timestamp", 
    "0501": "height", 
    "0504": "element_ID",
    "0502": "density", 
    "0503": "temperature", 
    "0506": "lwc",
    "0508": "dendricity", 
    "0509": "sphericity", 
    "0510": "coord_number",
    "0511": "bond_size", 
    "0512": "grain_size", 
    "0513": "grain_type",
    # "0514": "sh_at_surface",
    "0515": "ice_content", 
    "0516": "air_content",
    "0517": "stress", 
    "0518": "viscosity", 
    "0520": "temperature_gradient",
    "0523": "viscous_deformation_rate", 
    # "0530": "stab_indices",
    "0531": "stab_deformation_rate", 
    "0532": "sn38", 
    "0533": "sk38",
    "0534": "hand_hardness", 
    "0535": "opt_equ_grain_size",
    "0601": "shear_strength", 
    "0602": "gs_difference", 
    "0603": "hardness_difference",
    "0604": "ssi", 
    "1501": "height_nodes", 
    "1532": "sn38_nodes",
    "1533": "sk38_nodes", 
    "0540": "date_of_birth",
    "0607": "accumulated_temperature_gradient", 
    "9999": "rc_flat" # Placeholder for calculated rc_flat
}


class SnowpackProfile:
    """
    A class to read, parse, and represent SNOWPACK .pro files using xarray.

    This class handles the entire process of parsing a .pro file, transforming
    the data into a multi-dimensional xarray.Dataset, and providing methods
    for data access and analysis. Upon initialization, it automatically reads
    the file and computes the critical cut length (rc_flat) for all profiles.

    Attributes:
        filename (str): The path to the input .pro file.
        metadata (Dict): A dictionary containing station parameters parsed
            from the file's header (e.g., altitude, latitude).
        data (Optional[xr.Dataset]): An xarray Dataset containing all time-series
            profile data. It has dimensions 'timestamp' and 'layer_index'.
            This is None if parsing fails.
    """

    def __init__(self, filename: str):
        """
        Initializes the SnowpackProfile reader and loads the specified file.

        Args:
            filename (str): The full path to the .pro file.
        """
        self.filename: str = filename
        self.metadata: Dict = {}
        self.data: Optional[xr.Dataset] = None
        self._read_profile()

    def __len__(self) -> int:
        """
        Returns the number of profiles (timestamps) in the dataset.

        Returns:
            int: The number of unique timestamps.
        """
        if self.data is None: return 0
        return len(self.data.timestamp)

    def __repr__(self) -> str:
        """
        Provides a developer-friendly representation of the object.

        Returns:
            str: A string showing the class, filename, and profile count.
        """
        return f"<SnowpackProfile(filename='{self.filename}', profiles={len(self)})>"

    def __str__(self) -> str:
        """
        Provides a user-friendly summary of the snow profile data.

        Returns:
            str: A formatted string with station name, file path, number of
                 profiles, and available parameters.
        """
        if self.data is None:
            return f"SnowpackProfile for '{self.filename}' (no data loaded or failed to parse)"
        station_name = self.metadata.get('stationName', 'Unknown Station')
        return (f"Snow Profile for Station: '{station_name}'\n"
                f"File: '{self.filename}'\n"
                f"Available Profiles: {len(self)}\n"
                f"Parameters: {list(self.data.data_vars)}")

    def _read_profile(self):
        """
        Reads and parses the entire .pro file.

        This method iterates through the file, distinguishing between the header
        and data sections. It collects data for each timestamp and then
        orchestrates the creation of the main xarray.Dataset. Finally, it
        triggers the calculation of `rc_flat`.
        """
        if not os.path.exists(self.filename):
            logger.error(f"File not found: {self.filename}")
            return
        in_header, in_data = False, False
        temp_profiles: List[Dict] = []
        current_ts_data: Dict = {}
        
        with open(self.filename, 'r') as f:
            for line in tqdm(f, desc=f"Reading {os.path.basename(self.filename)}"):
                line = line.strip()
                if not line: continue
                
                # State management based on section headers
                if line == '[STATION_PARAMETERS]':
                    in_header, in_data = True, False
                elif line == '[DATA]':
                    in_header, in_data = False, True
                elif line.startswith('['):
                    in_header, in_data = False, False
                
                # Line processing based on current state
                elif in_header:
                    self._parse_header_line(line)
                elif in_data:
                    is_new_ts, timestamp_key = self._is_new_timestamp_line(line)
                    if is_new_ts:
                        # If a new timestamp is found, store the previous one
                        if current_ts_data:
                            temp_profiles.append(current_ts_data)
                        # Start a new data dictionary
                        current_ts_data = {'timestamp': timestamp_key}
                    else:
                        self._parse_data_line(line, current_ts_data)
        
        # Append the very last profile
        if current_ts_data:
            temp_profiles.append(current_ts_data)
            
        if not temp_profiles:
            logger.warning("No data was parsed from the file.")
            return
        
        self._create_dataset_from_profiles(temp_profiles)
        
        if self.data is not None:
            self._compute_and_add_rc_flat_vectorized()

    def _create_dataset_from_profiles(self, profiles: List[Dict]):
        """
        Converts a list of parsed profile dictionaries into an xarray.Dataset.

        This method handles the complexity of creating a multi-dimensional array
        from profiles with varying numbers of layers. It pads shorter profiles
        with NaNs to create a uniform array structure.

        Args:
            profiles (List[Dict]): A list where each dictionary holds the data
                                   for one timestamp.
        """
        # Parse timestamps and filter out any profiles with invalid dates
        timestamps = pd.to_datetime([p['timestamp'] for p in profiles], format='%d.%m.%Y %H:%M:%S', errors='coerce')
        valid_indices = ~pd.isna(timestamps)
        profiles = [p for i, p in enumerate(profiles) if valid_indices[i]]
        timestamps = timestamps.dropna()
        
        if not profiles:
            logger.warning("No valid profiles remaining after date parsing.")
            return

        # Determine all parameters present and the max number of layers across all profiles
        all_params = sorted(list(set(key for p in profiles for key in p if key != 'timestamp')))
        max_layers = max((len(p.get('height', [])) for p in profiles), default=0)
        
        # Pre-allocate numpy arrays for each parameter, filled with NaNs
        data_vars = {
            param: (("timestamp", "layer_index"), np.full((len(profiles), max_layers), np.nan))
            for param in all_params
        }
        
        # Populate the pre-allocated arrays with data from each profile
        for i, profile in enumerate(tqdm(profiles, desc="Creating Dataset")):
            num_layers = len(profile.get('height', []))
            for param, (dims, arr) in data_vars.items():
                if param in profile:
                    values = profile.get(param)
                    if values is not None and isinstance(values, np.ndarray):
                        # Place the layer data into the correct slice of the main array
                        arr[i, :num_layers] = values[:num_layers]

        # Create the final xarray Dataset
        self.data = xr.Dataset(
            data_vars,
            coords={'timestamp': timestamps, 'layer_index': np.arange(max_layers)}
        ).dropna(dim='timestamp', how='all')
        
        # Ensure data is sorted by time for correct time-series analysis
        if 'timestamp' in self.data.coords:
            self.data = self.data.sortby('timestamp')


    def _parse_header_line(self, line: str):
        """
        Parses a single line from the [STATION_PARAMETERS] section.

        Args:
            line (str): A line of text from the file header.
        """
        for key, value in HEADER_MAP.items():
            if line.startswith(key):
                try:
                    self.metadata[value] = line.split('=', 1)[1].strip()
                except IndexError:
                    logger.warning(f"Could not parse header line: {line}")

    def _is_new_timestamp_line(self, line: str) -> Tuple[bool, Optional[str]]:
        """
        Checks if a data line marks the beginning of a new profile.

        Args:
            line (str): A line of text from the [DATA] section.

        Returns:
            Tuple[bool, Optional[str]]: A tuple containing a boolean indicating
            if it's a new timestamp, and the timestamp string itself if it is.
        """
        parts = line.split(',', 1)
        if parts[0] == "0500": # '0500' is the code for a timestamp
            return True, parts[1]
        return False, None

    def _parse_data_line(self, line: str, current_ts_data: Dict):
        """
        Parses a single data line (a layer of a profile).

        Args:
            line (str): A comma-separated line containing a parameter code and its values.
            current_ts_data (Dict): The dictionary for the current timestamp being built.
        """
        try:
            parts = line.split(',')
            code = parts[0]
            param_name = PARAM_CODES.get(code)
            if param_name:
                # Convert all data points to a float numpy array
                values = np.array(parts[2:], dtype=float)
                current_ts_data[param_name] = values
        except (ValueError, IndexError) as e:
            logger.warning(f"Could not parse data line: '{line}' - Error: {e}")

    def _compute_and_add_rc_flat_vectorized(self):
        """
        Calculates rc_flat for all profiles in a single vectorized operation.
        ... (docstring remains the same) ...
        """
        # 1. --- Prerequisite Check ---
        required_vars = {'density', 'grain_size', 'shear_strength', 'height'}
        if not required_vars.issubset(self.data.data_vars):
            missing = required_vars - set(self.data.data_vars)
            logger.warning(f"Skipping rc_flat calculation due to missing data variables: {missing}")
            return

        # 2. --- Physical Constants ---
        RHO_ICE = 917.0    # Density of ice (kg/m^3)
        GS_0 = 0.00125     # A reference grain size (m)
        G = 9.81           # Acceleration due to gravity (m/s^2)
        A = 4.6e-9         # Empirical constant for viscosity calculation
        B = -2.0           # Empirical constant for viscosity calculation

        # 3. --- Data Preparation ---
        height = self.data['height']
        density = self.data['density']
        grain_size = self.data['grain_size']
        shear_strength = self.data['shear_strength']

        # 4. --- Slab Load Calculation (Sigma_n) ---

        # --- FIX: Replace .diff() with .shift() to avoid coordinate misalignment ---
        # The .diff() method was creating shifted coordinate labels, causing the AlignmentError.
        # This new method calculates thickness while preserving the original coordinates.
        height_of_bottom = height.shift(layer_index=1, fill_value=0)
        thick = height - height_of_bottom
        # --- End Fix ---

        layer_load = (density * thick * G)
        load = layer_load.reindex(layer_index=layer_load.layer_index[::-1]).cumsum(dim='layer_index').reindex(layer_index=layer_load.layer_index)

        # 5. --- Average Slab Density Calculation (rho_sl) ---
        total_thick_above = self.data['height'].max(dim='layer_index', skipna=True) - height
        with np.errstate(divide='ignore', invalid='ignore'):
            rho_sl = load / (total_thick_above * G)
        rho_sl = rho_sl.bfill(dim='layer_index').ffill(dim='layer_index')

        # 6. --- Intermediate Fracture Mechanics Calculations ---
        tau_p = shear_strength * 1000.0  # Shear strength from kPa to Pa
        gs = grain_size * 0.001       # Grain size from mm to m
        e_prime = 5.07e9 * (rho_sl / RHO_ICE)**5.13 / (1 - 0.2**2)
        dsl_over_sigman = 1.0 / (G * rho_sl)
        term1_under = A * (density / RHO_ICE * gs / GS_0)**B
        term2_under = 2 * tau_p * e_prime * dsl_over_sigman
        
        # 7. --- Final `rc_flat` Calculation ---
        term1 = np.sqrt(term1_under.where(term1_under > 0))
        term2 = np.sqrt(term2_under.where(term2_under > 0))
        rc_flat_da = (term1 * term2).fillna(9999.0)
        
        # Set rc_flat for the surface layer to 9999.0
        max_heights = height.max(dim='layer_index', skipna=True)
        is_not_surface = height < max_heights
        rc_flat_da = rc_flat_da.where(is_not_surface, 9999.0)

        # 8. --- Add to Dataset ---
        self.data['rc_flat'] = rc_flat_da.transpose('timestamp', 'layer_index')
        

    def list_timestamps(self) -> List[pd.Timestamp]:
        """
        Retrieves a list of all timestamps for the available profiles.

        Returns:
            List[pd.Timestamp]: A list of pandas Timestamp objects, sorted chronologically.
        """
        if self.data is None: return []
        return pd.to_datetime(self.data.timestamp.values)

    def profile_to_dataframe(self, timestamp: str) -> Optional[pd.DataFrame]:
        """
        Extracts a single profile for a given timestamp into a pandas DataFrame.

        If the exact timestamp is not found, it selects the profile with the
        nearest timestamp.

        Args:
            timestamp (str): The desired timestamp in a pandas-parsable format
                             (e.g., 'YYYY-MM-DD HH:MM:SS').

        Returns:
            Optional[pd.DataFrame]: A DataFrame where each row is a snow layer
            and columns are the snow parameters. Returns None if no data is
            available or the timestamp cannot be found.
        """
        if self.data is None:
            logger.warning("No data available in the reader.")
            return None
        try:
            # Use xarray's nearest-neighbor selection for robustness
            profile_data = self.data.sel(timestamp=timestamp, method='nearest')
            closest_ts = pd.to_datetime(profile_data.timestamp.values)
            logger.info(f"Requested timestamp '{timestamp}', found closest match: '{closest_ts.isoformat()}'")
        except (KeyError, ValueError) as e:
            logger.error(f"Could not find any timestamp near '{timestamp}': {e}")
            return None
        
        # Convert the selected xarray slice to a pandas DataFrame
        df = profile_data.to_dataframe().reset_index()
        df.dropna(subset=['height'], inplace=True) # Drop rows with no height data
        
        # Set height as the index for intuitive plotting and access
        if 'height' in df.columns:
            df.set_index('height', inplace=True)
            df = df[~df.index.duplicated(keep='last')]
            
        return df.drop(columns=['timestamp', 'layer_index'], errors='ignore')


    def get_profile_summary(self, parameters_to_calculate: Dict[str, any], from_height: Optional[float] = None, above_or_below: str = 'above', start_date: Optional[str] = None, end_date: Optional[str] = None) -> pd.DataFrame:
        """
        Extracts summary statistics for specified parameters within a given date range.

        This method processes the profile closest to noon for each day to ensure
        a consistent daily snapshot. It calculates the specified aggregate
        (e.g., 'min', 'max', 'mean') for each parameter and returns a DataFrame
        where each row represents one day.

        Args:
            parameters_to_calculate (Dict[str, any]): A dictionary mapping a
                new column name to a calculation type. The type can be a string
                ('min', 'max', 'mean', 'median', 'weighted_mean', 'weighted_sum')
                or a callable function (e.g., a lambda) that accepts a DataFrame
                of a single profile and returns a scalar value.
            from_height (Optional[float], optional): The height in meters to
                slice the snowpack. If None, the entire profile is used.
                Defaults to None.
            above_or_below (str, optional): Determines whether to analyze the
                section 'above' or 'below' the `from_height`. Must be either
                'above' or 'below'. Defaults to 'above'.
            start_date (Optional[str], optional): The start date for the summary
                period (inclusive), in a pandas-parsable format (e.g., 'YYYY-MM-DD').
                If None, the summary starts from the first available date.
                Defaults to None.
            end_date (Optional[str], optional): The end date for the summary
                period (inclusive), in a pandas-parsable format (e.g., 'YYYY-MM-DD').
                If None, the summary includes data up to the last available date.
                Defaults to None.

        Returns:
            pd.DataFrame: A wide-format DataFrame with a 'date' column and
            columns for each requested summary statistic. Returns an empty DataFrame
            if no noon profiles are found in the specified date range.

        Raises:
            ValueError: If 'above_or_below' is not 'above' or 'below'.
        """
        if not isinstance(parameters_to_calculate, dict):
            raise TypeError("Input 'parameters_to_calculate' must be a dictionary.")

        if from_height is not None and above_or_below not in ['above', 'below']:
            raise ValueError("Argument 'above_or_below' must be either 'above' or 'below'.")

        if self.data is None or self.data.timestamp.size == 0:
            logger.warning("No profile data loaded to generate summary.")
            return pd.DataFrame()

        data_in_range = self.data
        if start_date or end_date:
            try:
                s_date = pd.to_datetime(start_date) if start_date else None
                e_date = pd.to_datetime(end_date) if end_date else None
                time_slice = slice(s_date, e_date)
                data_in_range = data_in_range.sel(timestamp=time_slice)
            except Exception as e:
                logger.error(f"Failed to slice data with provided date range. Error: {e}")
                return pd.DataFrame()

        if data_in_range.timestamp.size == 0:
            logger.warning("No profile data found in the specified date range.")
            return pd.DataFrame()

        full_df = data_in_range.to_dataframe().reset_index()

        noon_time = full_df['timestamp'].dt.normalize() + pd.Timedelta(hours=12)
        full_df['time_from_noon'] = (full_df['timestamp'] - noon_time).abs()

        closest_indices = full_df.loc[full_df.groupby(full_df['timestamp'].dt.date)['time_from_noon'].idxmin()]
        noon_df = closest_indices.copy()

        if noon_df.empty:
            logger.warning("No daily profiles could be identified in the date range. Cannot generate summary.")
            return pd.DataFrame()

        noon_df['date'] = noon_df['timestamp'].dt.normalize()

        summary_list = []
        for timestamp in noon_df['timestamp']:
            summary_row = {'date': timestamp.normalize()}
            profile_layers = full_df[full_df['timestamp'] == timestamp].copy()

            if from_height is not None:
                profile_layers = profile_layers[profile_layers['height'] >= from_height] if above_or_below == 'above' else profile_layers[profile_layers['height'] < from_height]

            if not profile_layers.empty:
                profile_layers = profile_layers.sort_values('height').copy()
                profile_layers['thickness'] = profile_layers['height'].diff()
                base_h = from_height if (from_height is not None and above_or_below == 'above') else 0

                if not profile_layers.empty:
                    first_row_index = profile_layers.index[0]
                    first_row_height = profile_layers['height'].iloc[0]
                    profile_layers.loc[first_row_index, 'thickness'] = first_row_height - base_h

            for name, calc in parameters_to_calculate.items():
                if callable(calc):
                    try:
                        summary_row[name] = calc(profile_layers)
                    except Exception as e:
                        logger.warning(f"Custom function for '{name}' failed on {timestamp.date()}: {e}")
                    continue

                param, calc_type = name.split('-') if '-' in name else (name, None)
                if not calc_type: calc_type = calc

                if isinstance(calc_type, tuple):
                    param, calc_type = calc_type

                if param in profile_layers.columns:
                    series = profile_layers[param].dropna()
                    if series.empty: continue

                    if calc_type == 'mean':
                        summary_row[name] = series.mean()
                    elif calc_type == 'median':
                        summary_row[name] = series.median()
                    elif calc_type == 'min':
                        summary_row[name] = series.min()
                        if 'height' in profile_layers.columns and not series.empty:
                            summary_row[f"{name}-height"] = profile_layers.loc[series.idxmin()]['height']
                    elif calc_type == 'max':
                        summary_row[name] = series.max()
                        if 'height' in profile_layers.columns and not series.empty:
                            summary_row[f"{name}-height"] = profile_layers.loc[series.idxmax()]['height']
                    elif calc_type in ['weighted_mean', 'weighted_sum']:
                        weights = profile_layers.loc[series.index]['thickness']
                        weighted_sum_val = (series * weights).sum()
                        if calc_type == 'weighted_sum':
                            summary_row[name] = weighted_sum_val
                        elif weights.sum() > 0:
                            summary_row[name] = weighted_sum_val / weights.sum()

            summary_list.append(summary_row)

        if not summary_list: return pd.DataFrame()
        return pd.DataFrame(summary_list).set_index('date')
    

if __name__ == "__main__":
    # --- Example Usage ---
    # This block demonstrates a multi-step analysis:
    # 1. Find the daily minimum critical cut length (rc_flat) and its height.
    # 2. For each day, analyze the slab *above* that weak layer.
    # 3. Calculate the slab's weighted mean density (built-in stat) and
    #    a custom hand hardness metric (custom function).
    
    logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
    from glob import glob
    
    try:
        # Update this path to your data directory
        pro_files = glob("../data/snowpack/output/2024/**/*.pro", recursive=True)
        if not pro_files:
            raise FileNotFoundError("No .pro files found. Please update the glob path.")
        
        pro_path = np.random.choice(pro_files)
        logger.info(f"Selected file for demonstration: {pro_path}")
        
    except (FileNotFoundError, IndexError) as e:
        logger.error(f"Error finding a file to test: {e}. Please ensure files exist.")
        pro_path = None

    if pro_path:
        try:
            reader = SnowpackProfile(pro_path)
            print(f"\n{str(reader)}\n")

            # --- Step 1: Find the primary weak layer for each day ---
            print("--- Step 1: Locating the weakest layer (min rc_flat) for each day ---")
            # The .pro year file is for the water year 2024, so we analyze February 2025
            weak_layer_df = reader.get_profile_summary(
                parameters_to_calculate={'rc_flat': 'min',
                                         'height': 'max'},
                start_date='2025-02-01',
                end_date='2025-02-28'
            )
            # Rename the height column for clarity
            weak_layer_df.rename(columns={'rc_flat-height': 'weak_layer_height'}, inplace=True)
            
            if weak_layer_df.empty:
                raise ValueError("No weak layer data found for the date range.")
            
            print("Weak layer location summary (first 5 days):")
            print(weak_layer_df.head())

            # --- Step 2: Analyze the slab properties above the weak layer ---
            print("\n--- Step 2: Analyzing the slab above the weak layer for each day ---")
            slab_analysis_results = []

            # Iterate through each day we have weak layer data for
            for date, row in tqdm(weak_layer_df.iterrows(), total=weak_layer_df.shape[0], desc="Analyzing Slabs"):
                weak_layer_height = row['weak_layer_height']
                
                # Run a new summary for this single day, focusing on the slab
                slab_summary = reader.get_profile_summary(
                    start_date=date.strftime('%Y-%m-%d'),
                    end_date=date.strftime('%Y-%m-%d'),
                    from_height=weak_layer_height,
                    above_or_below='above',
                    parameters_to_calculate={
                        # Use a built-in stat for weighted mean density
                        'slab_density_weighted_mean': ('density', 'weighted_mean'),
                        # Use a custom function for the specific hand hardness formula
                        'slab_log_hardness_mean': lambda df: (2**df['hand_hardness'] * df['thickness']).mean() if not df.empty and 'hand_hardness' in df else None
                    }
                )

                if not slab_summary.empty:
                    slab_analysis_results.append(slab_summary.iloc[0])

            # --- Step 3: Combine and display the results ---
            if slab_analysis_results:
                slab_df = pd.DataFrame(slab_analysis_results)
                # Combine the weak layer info with the slab analysis info
                final_df = weak_layer_df.join(slab_df, how='inner')

                print("\n--- Step 3: Combined Daily Weak Layer and Slab Analysis ---")
                print(final_df.head())
            else:
                print("\nCould not perform slab analysis.")

        except Exception as e:
            logger.error(f"An error occurred during analysis: {e}", exc_info=True)